
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";




const AI_finanzkompass = lazy(() => import("./pages/AI_finanzkompass.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Content1 = lazy(() => import("./pages/Content1.tsx"));
const CorporateDashboard = lazy(() => import("./pages/CorporateDashboard.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Datenschutz = lazy(() => import("./pages/Datenschutz.tsx"));
const Deepdive_Nachfolgeplanung = lazy(() => import("./pages/Deepdive_Nachfolgeplanung.tsx"));
const DrMarkusVossProfilePage = lazy(() => import("./pages/DrMarkusVossProfilePage.tsx"));
const Impressum = lazy(() => import("./pages/Impressum.tsx"));
const Insights = lazy(() => import("./pages/Insights.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const RheinbergPrivatbankCorporatePage = lazy(() => import("./pages/RheinbergPrivatbankCorporatePage.tsx"));
const RheinbergPrivatbankProfilePage = lazy(() => import("./pages/RheinbergPrivatbankProfilePage.tsx"));
const RheinbergPrivatbankUserPage = lazy(() => import("./pages/RheinbergPrivatbankUserPage.tsx"));
const Signup = lazy(() => import("./pages/Signup.tsx"));
const TrustedAdvisorsPage = lazy(() => import("./pages/TrustedAdvisorsPage.tsx"));
const UserInterestsSelector_preview = lazy(() => import("./pages/UserInterestsSelector_preview.tsx"));
const V2_artikel_rheinberg = lazy(() => import("./pages/V2_artikel_rheinberg.tsx"));

export const userRoutes: RouteObject[] = [



	{ path: "/ai-finanzkompass", element: <AI_finanzkompass />},
	{ path: "/ai_finanzkompass", element: <AI_finanzkompass />},
	{ path: "/", element: <App />},
	{ path: "/content1", element: <Content1 />},
	{ path: "/corporate-dashboard", element: <CorporateDashboard />},
	{ path: "/corporatedashboard", element: <CorporateDashboard />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/datenschutz", element: <Datenschutz />},
	{ path: "/deepdive-nachfolgeplanung", element: <Deepdive_Nachfolgeplanung />},
	{ path: "/deepdive_nachfolgeplanung", element: <Deepdive_Nachfolgeplanung />},
	{ path: "/dr-markus-voss-profile-page", element: <DrMarkusVossProfilePage />},
	{ path: "/drmarkusvossprofilepage", element: <DrMarkusVossProfilePage />},
	{ path: "/impressum", element: <Impressum />},
	{ path: "/insights", element: <Insights />},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <Logout />},
	{ path: "/rheinberg-privatbank-corporate-page", element: <RheinbergPrivatbankCorporatePage />},
	{ path: "/rheinbergprivatbankcorporatepage", element: <RheinbergPrivatbankCorporatePage />},
	{ path: "/rheinberg-privatbank-profile-page", element: <RheinbergPrivatbankProfilePage />},
	{ path: "/rheinbergprivatbankprofilepage", element: <RheinbergPrivatbankProfilePage />},
	{ path: "/rheinberg-privatbank-user-page", element: <RheinbergPrivatbankUserPage />},
	{ path: "/rheinbergprivatbankuserpage", element: <RheinbergPrivatbankUserPage />},
	{ path: "/signup", element: <Signup />},
	{ path: "/trusted-advisors-page", element: <TrustedAdvisorsPage />},
	{ path: "/trustedadvisorspage", element: <TrustedAdvisorsPage />},
	{ path: "/user-interests-selector-preview", element: <UserInterestsSelector_preview />},
	{ path: "/userinterestsselector_preview", element: <UserInterestsSelector_preview />},
	{ path: "/v2-artikel-rheinberg", element: <V2_artikel_rheinberg />},
	{ path: "/v2_artikel_rheinberg", element: <V2_artikel_rheinberg />},

];
